[project]
site_name = "Doce GSR 2026.1"
site_description = "Documentação estudantil de Gerência e Segurança de Redes de Computadores."

site_author = "Fabiano Silva & Bruno Seabra"
site_url = "https://datalinker-ifrn.github.io/doce-gsr/"

repo_url = "https://github.com/datalinker-ifrn/doce-gsr"
edit_uri = "edit/main/docs/"

copyright = """
Copyright &copy; 2026 The authors
"""
# Read more: https://zensical.org/docs/setup/navigation/
# nav = [
#   { "Get started" = "index.md" },
#   { "Markdown in 5min" = "markdown.md" },
# ]

nav = [
  "index.md",

  { "Serviços de Rede" = [
      "servicos/firewall.md",
      "servicos/ldap.md",
      "servicos/ssh.md",
      "servicos/vpn.md",
      "servicos/zabbix.md",
    ]
  },

  { "Tutorial" = [
      "tutorial/index.md",
      "tutorial/markdown.md",
      "tutorial/exemplos.md",
      "tutorial/ferramentas.md",
    ]
  }
]

#extra_css = ["stylesheets/extra.css"]

#extra_javascript = ["javascripts/extra.js"]

[project.theme]

#variant = "classic"
#favicon = "images/favicon.png"
language = "pt-BR"

features = [
  "announce.dismiss",
  "content.action.edit",
  "content.action.view",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  #"header.autohide",
  #"navigation.expand",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  #"navigation.instant.progress",
  "navigation.path",
  #"navigation.prune",
  "navigation.sections",
  #"navigation.tabs",
  #"navigation.tabs.sticky",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",

]

[project.theme.icon]
logo = "lucide/smile"
edit = "material/pencil"
view = "material/eye"

#[project.theme.font]
#text = "Inter"
#code = "Jetbrains Mono"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
